### ISSUE TITLE
[Bug] PokeRandoZX-v4_6_0+V0_9_4 - FileNotFoundException

### ISSUE THREAD

**Issue by morgansmnm** [voliol/universal-pokemon-randomizer#1]
**Describe the bug**
Cannot save randomized ROM. Text "Saving" continues to cycle forever, but Command Prompt displays error:  java.io.FileNotFoundException: Gen2BrightTypeColors.txt (The system cannot find the file specified)

**To Reproduce**
1. Run Launcher_Windows
2. Load Pokemon Gold ROM
3. Go to Graphics Tab and change to randomly follow type
4. Click Randomize (Save)

**Expected behavior**
Expected to be able to save a modified version of the ROM file

**Screenshots**
<img width="1669" alt="Screenshot 2023-11-25 144427" src="https://github.com/voliol/universal-pokemon-randomizer/assets/34687722/a8393d7f-418f-498b-9455-41801639eb70">

**System (please complete the following information):**
 - Operating System: Windows 11
 - Java Version: Version 8 Update 371
 - Randomizer Version: [Bug] PokeRandoZX-v4_6_0+V0_9_4

**Additional context**
Could not get randomizer save on Windows 10 machine attempting to randomize Soul Silver or Black either. Gets stuck in "saving" loop forever.

**Comment by morgansmnm** [comment]
When attempting to run Black through the randomizer:

java.lang.IllegalArgumentException: File "OtherPokemonGraphics" does not exist.


Caused by: java.io.FileNotFoundException: Gen3to5TypeColors.txt (The system cannot find the file specified)

**Comment by morgansmnm** [comment]
Blue, however, was able to randomize perfectly

**Comment by voliol** [comment]
Thank you for the well written bug report, and sorry for seeing it first now. I should be able to get to it after Christmas.

Did the bug prevent you from randomizing the affected games at all, or was it only with palette randomization options selected?

**Comment by morgansmnm** [comment]
No worries at all. For every one I tried (except for blue), it freezes the randomization process. No corrupted files are made, but the program itself seems to load forever

**Comment by voliol** [comment]
Got a new version out, containing a fix: https://github.com/voliol/universal-pokemon-randomizer/releases/tag/v4.6.0%2BV0.10.0
