### ISSUE TITLE
New randomization vanilla features for wild Pokemon doesn't seem to respect 'similar Pokemon Strength' setting

### ISSUE THREAD

**Issue by ScienceTynan** [voliol/universal-pokemon-randomizer#2]
Hi, I really like the new features on the new release, especially the new features to maintain similar encounter types as in Vanilla games, but randomize them, but I'm having issues matching similar strength settings with the new features.

**To reproduce:**

Open Rom: 'Pokemon White' into Randomizer
Change the Wild Pokemon Settings to: "Area 1-1 Mapping and Keep Primary type selected. Similar Strength and Balance Shaking Grass Pokemon selected."
Open the log file containing the Pokemon Wild Pokemon data

**Expected behavior**: For the Wild Pokemon data to maintain types similar to the original game, and have similar BST totals as in the original, but have the Pokemon be randomized.

**Observed behaviour:** Types displaying correctly but high BST pokemon being introduced in many early game locations.

**System (please complete the following information):**

Operating System: Mac OS 14.3
Java Version: 20.0.2
Randomizer Version: PokeRandoZX-v4_6_0+V0_10_0

I'll attach a few examples. 

**This is with Area 1-1 Mapping and Keep Primary type selected. Similar Strength and Balance Shaking Grass Pokemon selected.**

<img width="540" alt="Screenshot 2024-01-09 at 4 17 45 PM" 
src="https://github.com/voliol/universal-pokemon-randomizer/assets/152658217/0708fbfa-3666-42be-bbbc-f20de39ae542">
<img width="540" alt="Screenshot 2024-01-09 at 4 17 56 PM" src="https://github.com/voliol/universal-pokemon-randomizer/assets/152658217/fea06796-359b-4476-bd07-7e3e69e5b67e">
<img width="540" alt="Screenshot 2024-01-09 at 4 18 11 PM" src="https://github.com/voliol/universal-pokemon-randomizer/assets/152658217/210fbfa1-3cda-41a7-83a0-e064fd76383f">

I see similar results when changing the mapping type or changing type restriction settings. I've also tried this with other Pokemon games and seem to have the same results.

No rush on this, but thought I'd bring it to your attention so it can be fixed in the future. Its possible I've applied the settings wrong, but thought I'd bring it to your attention anyways.

**Comment by voliol** [comment]
Hi ScienceTynan, thanks for your report!
Sadly I cannot reproduce the issue, are you sure those were the only options selected? Similar Strength is a low-priority option, so if used with e.g. "Catch 'em All Mode", where it tries to place all Pokémon somewhere, it should give similar results to yours.

**Comment by ScienceTynan** [comment]
> Hi ScienceTynan, thanks for your report! Sadly I cannot reproduce the issue, are you sure those were the only options selected? Similar Strength is a low-priority option, so if used with e.g. "Catch 'em All Mode", where it tries to place all Pokémon somewhere, it should give similar results to yours.

Weird. I did confirm that the Similar Strength setting does work in the previous version of the Randomizer, but I've tried just about every combination in version 0.10 (including not selecting any of these settings and only selecting the Similar strength option), it always gives me these unbalanced results. Catch 'em All Mode wasn't selected.

I tried it on my windows partition and got the same result too. I think I'm just going to wait for a future version to see if the issue resolves itself. It might just be my computer too.

In the meantime, the trainers maintaining the same typing does work, and of the two settings, I found that more useful to me. So I'm ok for now, but will keep trying in future updates.

**Comment by voliol** [comment]
This is a lesson to never try to reproduce bugs just in your testing environment ^^;. Turns out while the underlying logic worked, the checkbox for Similar Strength didn't... so it would simply never be turned on.

Fixed for the next version!
