### ISSUE TITLE
[Bug] Unable to swap static pokemon

### ISSUE THREAD

**Issue by blepblops** [voliol/universal-pokemon-randomizer#5]
**Describe the bug**
So while tracking down a bug I've been unable to recreate, I ran into an issue swapping static pokemon, outputting an error file.

**To Reproduce**
1. Load your favourite legal copy of Fire Red 1.1 (Also tested with Emerald)
2. In the "Starters, Statics & Trades" tab, under "Static Pokemon", select "Swap Legendaries & Swap Standards"
3. Attempt to randomize

**Expected behavior**
Clearly an error should not appear

**System (please complete the following information):**
 - Operating System: Win10
 - Java Version: 18.0.2.1
 - Randomizer Version: 0.12.0

**Additional context**
Error file attached here: 
[error_2024-06-19-13-27-28.txt](https://github.com/user-attachments/files/15899905/error_2024-06-19-13-27-28.txt)

**Comment by voliol** [comment]
This bug has been fixed in 0.12.0a
